#!/bin/sh

# We don't have eth0
uci -q del_list "network.@device[0].ports=eth0" 2>/dev/null || true
sed -i 's/"device": "eth0"/"device": "br-lan"/g' /etc/board.json

# Remove target-specific APK feed (msm89xx is not on downloads.openwrt.org)
sed -i '\|/targets/msm89xx/msm8916/packages|d' /etc/apk/repositories.d/distfeeds.list 2>/dev/null || true

/etc/init.d/wsdd2 enable
/etc/init.d/wsdd2 start

uci set system.@system[0].hostname='UZ801'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'

uci commit
